apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: eks-mongo-todo
spec:
  replicas: 1
  selector: { matchLabels: { app: todo-backend } }
  template:
    metadata: { labels: { app: todo-backend } }
    spec:
      imagePullSecrets:        # ta bort blocket om paketet är PUBLIC
        - name: ghcr-creds
      containers:
        - name: api
          image: ghcr.io/andreasvilhelmsson/todo-backend-v2:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]