apiVersion: apps/v1
kind: Deployment
metadata: { name: todo-backend, namespace: eks-mongo-todo }
spec:
  replicas: 1
  selector: { matchLabels: { app: todo-backend } }
  template:
    metadata: { labels: { app: todo-backend } }
    spec:
      containers:
        - name: api
          image: "%%IMAGE%%"
          env:
            - { name: ASPNETCORE_URLS, value: "http://+:8080" }
            - { name: MONGO_URI, value: "mongodb://root:changeme@mongodb:27017/?authSource=admin" }
          ports: [{ containerPort: 8080 }]