apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: eks-mongo-todo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector: { app: todo-frontend }
  ports:
    - port: 80
      targetPort: 80