apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: eks-mongo-todo
  labels: { app: mongo }
spec:
  replicas: 1
  selector:
    matchLabels: { app: mongo }
  template:
    metadata:
      labels: { app: mongo }
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports: [{ containerPort: 27017 }]
          env:
            - name: MONGO_INITDB_DATABASE
              value: todos
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          emptyDir: {}