apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: eks-mongo-todo
  labels:
    app: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017