name: build-backend

on:
  push:
    paths:
      - 'app/todo-backend/**'
      - '.github/workflows/backend-image.yml'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: ./app/todo-backend
          file: ./app/todo-backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/andreasvilhelmsson/todo-backend:0.1.${{ github.run_number }}
            ghcr.io/andreasvilhelmsson/todo-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max