name: build-backend

on:
  push:
    paths:
      - 'todo-backend/**'
      - '.github/workflows/backend-image.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./todo-backend
          file: ./todo-backend/dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/andreasvilhelmsson/todo-backend:0.1.${{ github.run_number }}